[book]
title = "CE-RISE Software Template Documentation"
authors = ["CE-RISE consortium"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://codeberg.org/CE-RISE-software/template-software"
sidebar-header-nav = true
additional-js = ["theme/custom.js"]
